version: 2.1
orbs:
  maven: circleci/maven@0.0.12
jobs:
  build:
    docker:
      - image: circleci/openjdk:17-jdk
    steps:
      - checkout
      - maven/with_cache:
          steps:
            - run: mvn dependency:go-offline
      - run: mvn test
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
               - main